-- Seed 8 professional referrals from novanhelme@gmail.com for admin dashboard testing.
-- Run once in Supabase SQL Editor (Dashboard → SQL Editor → New query → paste → Run).
-- referral_code is auto-generated by trigger on insert.
-- If you get an RLS/permission error, run as the service role or add a one-off migration that runs this.

INSERT INTO referral_submissions (
    referral_source_email,
    referral_source_name,
    referral_source_type,
    client_first_name,
    client_last_name,
    status,
    referral_source_organization,
    court_jurisdiction
) VALUES
    ('novanhelme@gmail.com', 'Nova Test', 'case_management', 'Alex', 'Smith', 'pending_review', 'Test Org', 'Denver District'),
    ('novanhelme@gmail.com', 'Nova Test', 'court', 'Jordan', 'Lee', 'pending_review', 'Court of Test', 'Boulder County'),
    ('novanhelme@gmail.com', 'Nova Test', 'legal_representative', 'Casey', 'Brown', 'pending_review', 'Legal Aid', NULL),
    ('novanhelme@gmail.com', 'Nova Test', 'mental_health_facility', 'Morgan', 'Davis', 'pending_review', 'MH Center', NULL),
    ('novanhelme@gmail.com', 'Nova Test', 'case_management', 'Riley', 'Wilson', 'pending_review', 'CM Agency', NULL),
    ('novanhelme@gmail.com', 'Nova Test', 'case_management', 'Sam', 'Taylor', 'pending_review', NULL, 'Arapahoe'),
    ('novanhelme@gmail.com', 'Nova Test', 'probation_parole', 'Jamie', 'Martinez', 'pending_review', 'Probation Dept', NULL),
    ('novanhelme@gmail.com', 'Nova Test', 'court', 'Quinn', 'Anderson', 'pending_review', 'Test Court', 'Jefferson County');
