#!/usr/bin/env npx tsx
/**
 * Sync canonical theme into Framer paste files.
 * 1. Generates monarchThemeInjectCss.ts from monarch-theme-inject.css
 * 2. Replaces // @monarch-theme:inline:start … end blocks in ReferralDashboard & ReferralSourcePortal
 *
 * Usage: npx tsx Code/theme/sync-framer-theme.ts
 */
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { COLORS, RADIUS, FONT, FONT_HEADING, SHADOWS, TRANSITION } from "./designTokens"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(__dirname, "../..")

const injectCssPath = path.join(__dirname, "monarch-theme-inject.css")
const injectTsPath = path.join(__dirname, "monarchThemeInjectCss.ts")

const framerTargets = [
    path.join(repoRoot, "Code/Framer/ReferralDashboard.tsx"),
    path.join(repoRoot, "Code/Framer/ReferralSourcePortal.tsx"),
]

const START = "// @monarch-theme:inline:start"
const END = "// @monarch-theme:inline:end"

function read(file: string) {
    return fs.readFileSync(file, "utf8")
}

function write(file: string, content: string) {
    fs.writeFileSync(file, content, "utf8")
}

function escapeTemplateLiteral(s: string) {
    return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${")
}

function serializeObjectConst(name: string, obj: Record<string, string>) {
    const lines = Object.entries(obj).map(([k, v]) => `    ${k}: ${JSON.stringify(v)},`)
    return `const ${name} = {\n${lines.join("\n")}\n}`
}

function buildFramerInlineBlock(injectCss: string) {
    return `${START} — generated by npx tsx Code/theme/sync-framer-theme.ts; edit Code/theme/ instead
const MONARCH_THEME_INJECT_CSS = \`${escapeTemplateLiteral(injectCss)}\`

const MONARCH_THEME_STORAGE_KEY = "monarch-dashboard-theme"

type MonarchThemeMode = "light" | "dark" | "system"

function getStoredMonarchThemeMode(): MonarchThemeMode {
    try {
        const stored = localStorage.getItem(MONARCH_THEME_STORAGE_KEY)
        if (stored === "light" || stored === "dark" || stored === "system") return stored
    } catch {
        /* ignore */
    }
    return "system"
}

function resolveMonarchThemeMode(mode: MonarchThemeMode): "light" | "dark" {
    if (mode === "light" || mode === "dark") return mode
    return typeof window !== "undefined" && window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light"
}

function applyMonarchThemeMode(mode: MonarchThemeMode): "light" | "dark" {
    const resolved = resolveMonarchThemeMode(mode)
    if (typeof document !== "undefined") {
        document.documentElement.classList.toggle("dark", resolved === "dark")
        document.documentElement.dataset.theme = resolved
    }
    try {
        localStorage.setItem(MONARCH_THEME_STORAGE_KEY, mode)
    } catch {
        /* ignore */
    }
    if (typeof window !== "undefined") {
        window.dispatchEvent(new CustomEvent("monarch-theme-change"))
    }
    return resolved
}

function useMonarchThemeBootstrap() {
    useEffect(() => {
        if (typeof document === "undefined") return
        const id = "monarch-dashboard-theme-vars"
        if (!document.getElementById(id)) {
            const el = document.createElement("style")
            el.id = id
            el.textContent = MONARCH_THEME_INJECT_CSS
            document.head.appendChild(el)
        }
        applyMonarchThemeMode(getStoredMonarchThemeMode())
        const mq = window.matchMedia("(prefers-color-scheme: dark)")
        const onSystemChange = () => {
            if (getStoredMonarchThemeMode() === "system") applyMonarchThemeMode("system")
        }
        mq.addEventListener("change", onSystemChange)
        return () => mq.removeEventListener("change", onSystemChange)
    }, [])
}

${serializeObjectConst("COLORS", COLORS as Record<string, string>)}
${serializeObjectConst("RADIUS", RADIUS as Record<string, string>)}
const FONT = ${JSON.stringify(FONT)}
const FONT_HEADING = ${JSON.stringify(FONT_HEADING)}
${serializeObjectConst("SHADOWS", SHADOWS as Record<string, string>)}
const TRANSITION = ${JSON.stringify(TRANSITION)}
${END}`
}

const THEME_RENAMES: Array<[RegExp, string]> = [
    [/\buseDashboardThemeBootstrap\b/g, "useMonarchThemeBootstrap"],
    [/\busePortalThemeBootstrap\b/g, "useMonarchThemeBootstrap"],
    [/\bgetStoredDashboardThemeMode\b/g, "getStoredMonarchThemeMode"],
    [/\bgetStoredPortalThemeMode\b/g, "getStoredMonarchThemeMode"],
    [/\bresolveDashboardThemeMode\b/g, "resolveMonarchThemeMode"],
    [/\bresolvePortalThemeMode\b/g, "resolveMonarchThemeMode"],
    [/\bapplyDashboardThemeMode\b/g, "applyMonarchThemeMode"],
    [/\bapplyPortalThemeMode\b/g, "applyMonarchThemeMode"],
    [/\bDashboardThemeMode\b/g, "MonarchThemeMode"],
    [/\bPortalThemeMode\b/g, "MonarchThemeMode"],
    [/\bDASHBOARD_THEME_STORAGE_KEY\b/g, "MONARCH_THEME_STORAGE_KEY"],
    [/\bPORTAL_THEME_STORAGE_KEY\b/g, "MONARCH_THEME_STORAGE_KEY"],
]

function applyThemeRenames(src: string) {
    let out = src
    for (const [re, replacement] of THEME_RENAMES) {
        out = out.replace(re, replacement)
    }
    return out
}

function migrateDashboardThemeBlock(src: string): string {
    if (src.includes(START)) return src
    return src.replace(
        /\/\/ ----- Inlined design system \(no import\)[\s\S]*?const TRANSITION = "all 0.2s ease"\n/,
        `${START} — pending sync\n${END}\n`
    )
}

function migratePortalThemeBlock(src: string): string {
    if (src.includes(START)) return src
    let out = src.replace(
        /\/\/ ----- Inlined design system \(no import\)[\s\S]*?const FONT_HEADING = [^\n]+\n/,
        `${START} — pending sync\n${END}\n`
    )
    out = out.replace(
        /const (?:PORTAL|DASHBOARD)_THEME_STORAGE_KEY[\s\S]*?function use(?:Portal|Dashboard)ThemeBootstrap\(\) \{[\s\S]*?\n\}\n\n/,
        ""
    )
    out = out.replace(/const PORTAL_THEME_CSS = `[\s\S]*?`\n\n/, "")
    out = out.replace(/const DASHBOARD_THEME_CSS = `[\s\S]*?`\n\n/, "")
    out = out.replace(
        /const COLORS = \{[\s\S]*?\}\nconst RADIUS = \{[\s\S]*?\}\nconst FONT = [^\n]+\nconst FONT_HEADING = [^\n]+\n(?:const SHADOWS = \{[\s\S]*?\}\nconst TRANSITION = [^\n]+\n\n)?/,
        ""
    )
    out = out.replace(
        /const TABLE_COLUMN_HEADER_STYLE[\s\S]*?letterSpacing: "0.004em",\n\}\nconst SHADOWS = \{[\s\S]*?\}\nconst TRANSITION = [^\n]+\n\n/,
        (m) => m.replace(/const SHADOWS = \{[\s\S]*?\}\nconst TRANSITION = [^\n]+\n\n/, "")
    )
    return out
}

function ensureMarkers(filePath: string): boolean {
    const rel = path.relative(repoRoot, filePath)
    let src = read(filePath)
    const before = src
    if (rel.includes("ReferralDashboard")) src = migrateDashboardThemeBlock(src)
    if (rel.includes("ReferralSourcePortal")) src = migratePortalThemeBlock(src)
    if (src !== before) {
        write(filePath, src)
        console.log("Migrated markers in", rel)
        return true
    }
    return src.includes(START) && src.includes(END)
}

function patchFramerFile(filePath: string, inlineBlock: string) {
    ensureMarkers(filePath)
    let src = read(filePath)
    const startIdx = src.indexOf(START)
    const endIdx = src.indexOf(END)

    if (startIdx === -1 || endIdx === -1) {
        console.warn(`Skip ${path.relative(repoRoot, filePath)}: markers not found`)
        return false
    }

    const before = src.slice(0, startIdx)
    const after = src.slice(endIdx + END.length)
    src = applyThemeRenames(before + inlineBlock + after)
    write(filePath, src)
    return true
}

function main() {
    const injectCss = read(injectCssPath)

    write(
        injectTsPath,
        `/** Auto-generated — do not edit. Run: npx tsx Code/theme/sync-framer-theme.ts */\nexport const MONARCH_THEME_INJECT_CSS = \`${escapeTemplateLiteral(injectCss)}\`\n`
    )
    console.log("Wrote", path.relative(repoRoot, injectTsPath))

    const inlineBlock = buildFramerInlineBlock(injectCss)
    let patched = 0
    for (const target of framerTargets) {
        if (patchFramerFile(target, inlineBlock)) {
            console.log("Patched", path.relative(repoRoot, target))
            patched++
        }
    }

    if (patched === 0) {
        console.log("No Framer files patched. Insert markers, then re-run.")
        process.exitCode = 1
    }
}

main()
