import type { MockOrganization } from "./types"

export const INITIAL_MOCK_ORGANIZATIONS: MockOrganization[] = [
    {
        id: "org-1",
        name: "New Horizons",
        contact_name: "Såtta Brunar",
        phone: "(303) 555-0142",
        email: "satta@newhorizons.org",
        organization_type: "treatment_center",
        created_at: "2025-11-12",
    },
    {
        id: "org-2",
        name: "Daily Transistors",
        contact_name: "Taylor Brooks",
        phone: "(720) 555-0198",
        email: "taylor@dailytransistors.net",
        organization_type: "detention_center",
        created_at: "2025-12-03",
    },
    {
        id: "org-3",
        name: "Healthy Minds",
        contact_name: "Alex Rivera",
        phone: "(303) 555-2210",
        email: "alex@healthyminds.co",
        organization_type: "community_center",
        created_at: "2026-01-08",
    },
    {
        id: "org-4",
        name: "PALs Foundation",
        contact_name: "Pat Nguyen",
        phone: "(303) 555-8841",
        email: "pat.nguyen@palsfoundation.org",
        organization_type: "health_wellness",
        created_at: "2026-01-15",
    },
    {
        id: "org-5",
        name: "Megan Forever",
        contact_name: "Chris Allen",
        phone: "(720) 555-3309",
        email: "chris.allen@meganforever.org",
        organization_type: "county_jail",
        created_at: "2026-01-22",
    },
    {
        id: "org-6",
        name: "Big Ideas",
        contact_name: "Morgan Lee",
        phone: "(303) 555-7712",
        email: "morgan@bigideas.org",
        organization_type: "treatment_center",
        created_at: "2026-02-01",
    },
    {
        id: "org-7",
        name: "Building Blocks",
        contact_name: "Jamie Fox",
        phone: "(720) 555-4420",
        email: "jamie@buildingblocks.net",
        organization_type: "community_center",
        created_at: "2026-02-10",
    },
    {
        id: "org-8",
        name: "Pittsburgh Inc",
        contact_name: "Sam Ortiz",
        phone: "(303) 555-6618",
        email: "sam@pittsburghinc.org",
        organization_type: "legal_representative",
        created_at: "2026-02-18",
    },
    {
        id: "org-9",
        name: "Miles Apart",
        contact_name: "Casey Holt",
        phone: "(720) 555-9033",
        email: "casey@milesapart.co",
        organization_type: "health_wellness",
        created_at: "2026-03-02",
    },
    {
        id: "org-10",
        name: "Forever Forward",
        contact_name: "Maria Garcia",
        phone: "(303) 555-1187",
        email: "maria@foreverforward.org",
        organization_type: "treatment_center",
        created_at: "2026-03-12",
    },
    {
        id: "org-11",
        name: "Denver Courts",
        contact_name: "Alex Rivera",
        phone: "(303) 555-0100",
        email: "a.rivera@denvercourts.gov",
        organization_type: "court",
        created_at: "2026-02-11",
    },
    {
        id: "org-12",
        name: "Arapahoe Probation",
        contact_name: "Pat Nguyen",
        phone: "(720) 555-0200",
        email: "p.nguyen@arapahoegov.org",
        organization_type: "probation_parole",
        created_at: "2026-02-18",
    },
    {
        id: "org-13",
        name: "Colorado Bridges",
        contact_name: "Såtta Brunar",
        phone: "(303) 555-0142",
        email: "satta@coloradobridges.org",
        organization_type: "community_center",
        created_at: "2026-01-31",
    },
    {
        id: "org-14",
        name: "Community Center",
        contact_name: "Taylor Brooks",
        phone: "(303) 555-7788",
        email: "taylor@communitycenter.org",
        organization_type: "community_center",
        created_at: "2026-03-05",
    },
    {
        id: "org-15",
        name: "Hospital Psych",
        contact_name: "Casey Holt",
        phone: "(720) 555-4411",
        email: "casey.holt@hospitalpsych.org",
        organization_type: "treatment_center",
        created_at: "2026-05-24",
    },
]
