import type { MockReferral } from "./types"

export const INITIAL_MOCK_REFERRALS: MockReferral[] = [
    {
        id: "1",
        referral_code: "MON-A4K7",
        admin_ref_id: "REF-MC-076",
        status: "pending_review",
        client_first_name: "John",
        client_last_name: "Doe",
        referral_source_name: "Såtta Brunar",
        organization: "Colorado Bridges",
        referral_source_type: "case_management",
        program: "Competency",
        assigned_to_user_id: "staff-1",
        assignee_name: "Christina F.",
        transfer_status: "none",
        created_at: "2026-01-31",
        last_activity_at: "2026-05-28",
        urgent_placement: true,
        urgency_level: "asap",
        has_unread_messages: true,
        has_attachments: true,
    },
    {
        id: "2",
        referral_code: "MON-B2M1",
        admin_ref_id: "REF-MC-043",
        status: "under_review",
        client_first_name: "Jane",
        client_last_name: "Doe",
        referral_source_name: "Alex Rivera",
        organization: "Denver Courts",
        referral_source_type: "court",
        program: "Competency",
        assigned_to_user_id: "staff-1",
        assignee_name: "Christina F.",
        transfer_status: "pending_acceptance",
        pending_transfer_to_program: "Mental Health",
        created_at: "2026-02-11",
        last_activity_at: "2026-05-25",
        urgent_placement: false,
        adl_support_needed: true,
        has_attachments: true,
    },
    {
        id: "3",
        referral_code: "MON-C9P3",
        admin_ref_id: "REF-MC-051",
        status: "under_review",
        client_first_name: "Michael",
        client_last_name: "Smith",
        referral_source_name: "Pat Nguyen",
        organization: "Arapahoe Probation",
        referral_source_type: "probation_parole",
        program: "Mental Health",
        created_at: "2026-02-18",
        urgent_placement: true,
        urgency_level: "conditional_timeline",
        urgency_target_date: "2026-06-15",
        detox_required: "yes",
    },
    {
        id: "4",
        referral_code: "MON-D1X8",
        admin_ref_id: "REF-MC-062",
        status: "waitlisted",
        client_first_name: "Sarah",
        client_last_name: "Johnson",
        referral_source_name: "Morgan Lee",
        organization: "State Hospital",
        referral_source_type: "mental_health_facility",
        program: "Competency",
        assigned_to_user_id: "staff-4",
        assignee_name: "Jordan K.",
        transfer_status: "none",
        created_at: "2026-02-20",
        urgent_placement: false,
        has_attachments: true,
    },
    {
        id: "5",
        referral_code: "MON-E5Q2",
        admin_ref_id: "REF-MC-068",
        status: "accepted",
        client_first_name: "David",
        client_last_name: "Martinez",
        referral_source_name: "Chris Allen",
        organization: "County Jail",
        referral_source_type: "court",
        program: "Sober Living",
        assigned_to_user_id: "staff-1",
        assignee_name: "Christina F.",
        transfer_status: "none",
        created_at: "2026-03-01",
        urgent_placement: false,
    },
    {
        id: "6",
        referral_code: "MON-F7R4",
        admin_ref_id: "REF-MC-071",
        status: "declined",
        client_first_name: "Emily",
        client_last_name: "Chen",
        referral_source_name: "Taylor Brooks",
        organization: "Community Center",
        referral_source_type: "case_management",
        program: "Launch",
        created_at: "2026-03-05",
        urgent_placement: false,
    },
    {
        id: "7",
        referral_code: "MON-G2T9",
        admin_ref_id: "REF-MC-074",
        status: "pending_review",
        client_first_name: "Robert",
        client_last_name: "Williams",
        referral_source_name: "Jamie Fox",
        organization: "Treatment Facility",
        referral_source_type: "mental_health_facility",
        program: "Competency",
        created_at: "2026-05-20",
        urgent_placement: false,
    },
    {
        id: "8",
        referral_code: "MON-H8U1",
        admin_ref_id: "REF-MC-078",
        status: "pending_review",
        client_first_name: "Lisa",
        client_last_name: "Anderson",
        referral_source_name: "Sam Ortiz",
        organization: "Legal Aid",
        referral_source_type: "legal_representative",
        program: "Competency",
        created_at: "2026-05-22",
        urgent_placement: true,
        urgency_level: "conditional_timeline",
        urgency_target_date: "2026-05-31",
    },
    {
        id: "9",
        referral_code: "MON-J3V6",
        admin_ref_id: "REF-MC-080",
        status: "waitlisted",
        client_first_name: "James",
        client_last_name: "Brown",
        referral_source_name: "Riley Stone",
        organization: "DOC",
        referral_source_type: "probation_parole",
        program: "Mental Health",
        assignee_name: "Jordan K.",
        created_at: "2026-05-15",
        urgent_placement: false,
        has_attachments: true,
    },
    {
        id: "10",
        referral_code: "MON-K4W7",
        admin_ref_id: "REF-MC-082",
        status: "under_review",
        client_first_name: "Maria",
        client_last_name: "Garcia",
        referral_source_name: "Casey Holt",
        organization: "Hospital Psych",
        referral_source_type: "mental_health_facility",
        program: "Competency",
        created_at: "2026-05-24",
        urgent_placement: false,
        has_unread_messages: true,
        violence_risk: "recent",
        has_attachments: true,
    },
    // Extra cards for column scroll testing (New Referral)
    {
        id: "11",
        referral_code: "MON-D1N2",
        admin_ref_id: "REF-MC-091",
        status: "pending_review",
        client_first_name: "Elena",
        client_last_name: "Vasquez",
        referral_source_name: "Morgan Lee",
        organization: "Boulder County",
        referral_source_type: "court",
        program: "Competency",
        created_at: "2026-05-26",
        urgent_placement: false,
    },
    {
        id: "12",
        referral_code: "MON-E3Q4",
        admin_ref_id: "REF-MC-092",
        status: "pending_review",
        client_first_name: "David",
        client_last_name: "Kim",
        referral_source_name: "Taylor Brooks",
        organization: "Jefferson Courts",
        referral_source_type: "court",
        program: "Mental Health",
        assignee_name: "Jordan K.",
        created_at: "2026-05-25",
        urgent_placement: true,
        urgency_level: "asap",
        has_attachments: true,
    },
    {
        id: "13",
        referral_code: "MON-F5R6",
        admin_ref_id: "REF-MC-093",
        status: "pending_review",
        client_first_name: "Sophia",
        client_last_name: "Martinez",
        referral_source_name: "Jamie Ortiz",
        organization: "Adams Probation",
        referral_source_type: "probation_parole",
        program: "Competency",
        created_at: "2026-05-24",
        urgent_placement: false,
        has_unread_messages: true,
    },
    {
        id: "14",
        referral_code: "MON-G7S8",
        admin_ref_id: "REF-MC-094",
        status: "pending_review",
        client_first_name: "Robert",
        client_last_name: "Chen",
        referral_source_name: "Dana Walsh",
        organization: "Larimer DOC",
        referral_source_type: "probation_parole",
        program: "Competency",
        created_at: "2026-05-23",
        urgent_placement: false,
        has_safety_flags: true,
        safety_flag_count: 1,
    },
    {
        id: "15",
        referral_code: "MON-H9T0",
        admin_ref_id: "REF-MC-095",
        status: "pending_review",
        client_first_name: "Olivia",
        client_last_name: "Nguyen",
        referral_source_name: "Chris Park",
        organization: "Weld County",
        referral_source_type: "court",
        program: "Mental Health",
        assignee_name: "Christina F.",
        created_at: "2026-05-22",
        urgent_placement: true,
        urgency_level: "conditional_timeline",
        has_attachments: true,
        has_unread_messages: true,
    },
    {
        id: "16",
        referral_code: "MON-J1U2",
        admin_ref_id: "REF-MC-096",
        status: "pending_review",
        client_first_name: "William",
        client_last_name: "Thompson",
        referral_source_name: "Sam Rivera",
        organization: "Douglas Courts",
        referral_source_type: "court",
        program: "Competency",
        created_at: "2026-05-21",
        urgent_placement: false,
    },
    {
        id: "17",
        referral_code: "MON-K3V4",
        admin_ref_id: "REF-MC-097",
        status: "pending_review",
        client_first_name: "Aisha",
        client_last_name: "Patel",
        referral_source_name: "Jordan Ellis",
        organization: "El Paso Probation",
        referral_source_type: "probation_parole",
        program: "Competency",
        created_at: "2026-05-20",
        urgent_placement: false,
        has_attachments: true,
    },
    {
        id: "18",
        referral_code: "MON-L5W6",
        admin_ref_id: "REF-MC-098",
        status: "pending_review",
        client_first_name: "Lucas",
        client_last_name: "Anderson",
        referral_source_name: "Riley Stone",
        organization: "Pueblo County",
        referral_source_type: "court",
        program: "Mental Health",
        created_at: "2026-05-19",
        urgent_placement: false,
    },
    // Extra cards for column scroll testing (Under Review)
    {
        id: "19",
        referral_code: "MON-M7X8",
        admin_ref_id: "REF-MC-099",
        status: "under_review",
        client_first_name: "Hannah",
        client_last_name: "Wilson",
        referral_source_name: "Alex Rivera",
        organization: "Denver Courts",
        referral_source_type: "court",
        program: "Competency",
        assignee_name: "Christina F.",
        created_at: "2026-05-18",
        urgent_placement: false,
        has_attachments: true,
    },
    {
        id: "20",
        referral_code: "MON-N9Y0",
        admin_ref_id: "REF-MC-100",
        status: "under_review",
        client_first_name: "Ethan",
        client_last_name: "Moore",
        referral_source_name: "Pat Nguyen",
        organization: "Arapahoe Probation",
        referral_source_type: "probation_parole",
        program: "Mental Health",
        created_at: "2026-05-17",
        urgent_placement: true,
        urgency_level: "asap",
    },
    {
        id: "21",
        referral_code: "MON-P1Z2",
        admin_ref_id: "REF-MC-101",
        status: "under_review",
        client_first_name: "Isabella",
        client_last_name: "Taylor",
        referral_source_name: "Casey Holt",
        organization: "Hospital Psych",
        referral_source_type: "mental_health_facility",
        program: "Competency",
        assignee_name: "Jordan K.",
        created_at: "2026-05-16",
        urgent_placement: false,
        has_unread_messages: true,
        has_safety_flags: true,
        safety_flag_count: 3,
    },
    {
        id: "22",
        referral_code: "MON-Q3A4",
        admin_ref_id: "REF-MC-102",
        status: "under_review",
        client_first_name: "Noah",
        client_last_name: "Jackson",
        referral_source_name: "Morgan Lee",
        organization: "Boulder County",
        referral_source_type: "court",
        program: "Competency",
        created_at: "2026-05-15",
        urgent_placement: false,
        has_attachments: true,
    },
    {
        id: "23",
        referral_code: "MON-R5B6",
        admin_ref_id: "REF-MC-103",
        status: "under_review",
        client_first_name: "Mia",
        client_last_name: "White",
        referral_source_name: "Taylor Brooks",
        organization: "Jefferson Courts",
        referral_source_type: "court",
        program: "Mental Health",
        created_at: "2026-05-14",
        urgent_placement: false,
    },
    {
        id: "24",
        referral_code: "MON-S7C8",
        admin_ref_id: "REF-MC-104",
        status: "under_review",
        client_first_name: "Benjamin",
        client_last_name: "Harris",
        referral_source_name: "Jamie Ortiz",
        organization: "Adams Probation",
        referral_source_type: "probation_parole",
        program: "Competency",
        assignee_name: "Christina F.",
        created_at: "2026-05-13",
        urgent_placement: true,
        urgency_level: "conditional_timeline",
        has_attachments: true,
        has_unread_messages: true,
    },
]
